# ==== CONFIGURE =====
# Use a Node 16 base image
FROM node:16-alpine 

WORKDIR '/app'

COPY package.json package-lock.json ./
RUN npm install -g serve
RUN npm ci

COPY . .

#RUN npm run-script build
# ==== RUN =======
# Set the env to "production"
ENV NODE_ENV production
# Expose the port on which the app will be running (3000 is the default that `serve` uses)
# Start the app
#CMD [ "npx", "serve", "build" ]
CMD [ "npm", "start" ]
